export { SMTPServer } from "./src/smtp-server.ts";
export type {
  SMTPServerOptions,
  SMTPServerEventMap,
  ConnectionInfo,
  SMTPSession,
  SMTPAddress,
  SMTPAddressArgs,
  AuthObject,
  AuthObjectPlain,
  AuthObjectCramMd5,
  AuthObjectXoauth2,
  AuthObjectXclient,
  AuthResponse,
  DataStream,
  OnConnectCallback,
  OnSecureCallback,
  OnAuthCallback,
  OnMailFromCallback,
  OnRcptToCallback,
  OnDataCallback,
  OnCloseCallback,
  SMTPError,
  TLSOptions,
} from "./src/types.ts";
