export { SMTPServer } from "./src/smtp-server.ts";
export type {
	AuthObject,
	AuthObjectCramMd5,
	AuthObjectPlain,
	AuthObjectXclient,
	AuthObjectXoauth2,
	AuthResponse,
	ConnectionInfo,
	DataStream,
	OnAuthCallback,
	OnCloseCallback,
	OnConnectCallback,
	OnDataCallback,
	OnMailFromCallback,
	OnRcptToCallback,
	OnSecureCallback,
	SMTPAddress,
	SMTPAddressArgs,
	SMTPError,
	SMTPServerEventMap,
	SMTPServerOptions,
	SMTPSession,
	TLSOptions,
} from "./src/types.ts";
